json.id circle.id
json.frame_id circle.frame_id
json.x circle.x.to_f
json.y circle.y.to_f
json.diameter circle.diameter.to_f
json.radius circle.radius.to_f
json.geometry circle.geometry
json.created_at circle.created_at
json.updated_at circle.updated_at
