openapi: 3.0.0
info:
  title: API V1
  version: v1
servers:
  - url: http://localhost:3013

paths:
  # Circles
  "/api/v1/circles":
    $ref: "./circles/listing.yaml"
  "/api/v1/circles/{id}":
    $ref: "./circles/update-destroy.yaml"
  # Frames
  "/api/v1/frames":
    $ref: "./frames/listing-create.yaml"
  "/api/v1/frames/{id}":
    $ref: "./frames/update-destroy.yaml"
  "/api/v1/frames/{frame_id}/circles":
    $ref: "./frames/circles/listing-create.yaml"

components:
  schemas:
