default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  database: <%= ENV.fetch('DATABASE_NAME') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  port: <%= ENV.fetch('DATABASE_PORT') %>
  username: <%= ENV.fetch('DATABASE_USERNAME') %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_TEST_NAME') %>

homolog:
  <<: *default

production:
  <<: *default
